import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pau' at '1/15/16 8:50 PM' with Gradle 2.8
 *
 * @author pau, @date 1/15/16 8:50 PM
 */
public class LibraryTest {

}
